### ISSUE TITLE
这个插件会导致现在版本的controlnet aux无法使用

### ISSUE THREAD

**Issue by whmc76** [AIFSH/ComfyUI-DiffSynth-Studio#3]
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/389

**Comment by shineway14** [comment]
无法加载controlnet_aux.processor

**Comment by klossm** [comment]
一样的情况，和controlnet aux插件有冲突

Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\__init__.py", line 2, in <module>
    from .studio_nodes import DiffTextNode,DiffutoonNode,SDPathLoader,ControlNetPathLoader,ExVideoNode
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\studio_nodes.py", line 11, in <module>
    from diffsynth.data.video import crop_and_resize
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\__init__.py", line 5, in <module>
    from .pipelines import *
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\__init__.py", line 1, in <module>
    from .stable_diffusion import SDImagePipeline
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\stable_diffusion.py", line 2, in <module>
    from ..controlnets import MultiControlNetManager, ControlNetUnit, ControlNetConfigUnit, Annotator
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\__init__.py", line 1, in <module>
    from .controlnet_unit import ControlNetConfigUnit, ControlNetUnit, MultiControlNetManager
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\controlnet_unit.py", line 3, in <module>
    from .processors import Processor_id
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\processors.py", line 7, in <module>
    from controlnet_aux.processor import (
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\processor.py", line 10, in <module>
    from controlnet_aux import (CannyDetector, ContentShuffleDetector, HEDdetector,
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

Cannot import L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio module for custom nodes: cannot import name 'CannyDetector' from 'controlnet_aux' (L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

**Comment by 66Cjj** [comment]
同样问题，和controlnet_aux冲突了。已经把comfyUI内核、comfyUI_aux、manage、本插件都更到最新了，但还是会发生冲突导致(IMPORT FAILED): D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio；我的环境是pytorch version: 2.1.1+cu118

Traceback (most recent call last):
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\__init__.py", line 2, in <module>
    from .studio_nodes import DiffTextNode,DiffutoonNode,SDPathLoader,ControlNetPathLoader,ExVideoNode
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\studio_nodes.py", line 11, in <module>
    from diffsynth.data.video import crop_and_resize
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\__init__.py", line 5, in <module>
    from .pipelines import *
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\__init__.py", line 1, in <module>
    from .stable_diffusion import SDImagePipeline
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\stable_diffusion.py", line 2, in <module>
    from ..controlnets import MultiControlNetManager, ControlNetUnit, ControlNetConfigUnit, Annotator
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\__init__.py", line 1, in <module>
    from .controlnet_unit import ControlNetConfigUnit, ControlNetUnit, MultiControlNetManager
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\controlnet_unit.py", line 3, in <module>
    from .processors import Processor_id
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\processors.py", line 7, in <module>
    from controlnet_aux.processor import (
  File "D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\processor.py", line 10, in <module>
    from controlnet_aux import (CannyDetector, ContentShuffleDetector, HEDdetector,
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

Cannot import D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DiffSynth-Studio module for custom nodes: cannot import name 'CannyDetector' from 'controlnet_aux' (D:\AI\TestDev\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

**Comment by jnc-nj** [comment]
pip uninstall controlnet-aux （虽然想法挺好，但这个包完全没有在maintain，估计是卖课的人搞的，还是官方的0.0.7左右的版本，不要装）
进comfyui_controlnet_aux/src/controlnet_aux/__init__.py将你要的包手动引入一次，也可以直接复制粘贴
```
from .anime_face_segment import *
from .binary import *
from .canny import *
from .color import *
from .densepose import *
from .depth_anything import *
from .depth_anything_v2 import *
from .diffusion_edge import *
from .dsine import *
from .dwpose import *
from .hed import *
from .leres import *
from .lineart import *
from .lineart_anime import *
from .lineart_standard import *
from .manga_line import *
from .mediapipe_face import *
from .mesh_graphormer import *
from .metric3d import *
from .midas import *
from .mlsd import *
from .normalbae import *
from .oneformer import *
from .open_pose import *
from .pidi import *
from .recolor import *
from .sam import *
from .scribble import *
from .shuffle import *
from .teed import *
from .tile import *
from .uniformer import *
from .unimatch import *
from .zoe import *
```
然后去comfyui_controlnet_aux手动重新pip install .一次让全局都能看到这个包
DiffSynth就能正常引用了
