### ISSUE TITLE
    if file_path.endswith(".safetensors"): AttributeError: 'NoneType' object has no attribute 'endswith' 

### ISSUE THREAD

**Issue by dancemanUK** [AIFSH/ComfyUI-DiffSynth-Studio#4]
!!! Exception during processing!!! 'NoneType' object has no attribute 'endswith'
Traceback (most recent call last):
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\studio_nodes.py", line 299, in maketoon
    model_manager.load_models([
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\models\__init__.py", line 476, in load_models
    self.load_model(file_path, lora_alphas=lora_alphas)
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\models\__init__.py", line 434, in load_model
    state_dict = load_state_dict(file_path, torch_dtype=self.torch_dtype)
  File "G:\comfyui\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\models\__init__.py", line 506, in load_state_dict
    if file_path.endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by dancemanUK** [comment]
custom_nodes\ComfyUI-DiffSynth-Studio\models\AnimateDiff\mm_sd_v15_v2.ckpt
